spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy.MM.dd HH:mm:ss
spring.datasource.url: jdbc:mysql://192.168.0.101/eventuate
spring.datasource.username: mysqluser
spring.datasource.password: mysqlpw
eventuateLocal.kafka.bootstrapServers: 192.168.0.101:9092
eventuateLocal.zookeeper.connectionString: 192.168.0.101:2181
eventuateLocal.cdc.dbUserName: root
eventuateLocal.cdc.dbPassword: rootpassword