spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy.MM.dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DOCKER_HOST_IP}/eventuate
    username: mysqluser
    password: mysqlpw
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eventuateLocal.kafka.bootstrapServers: ${DOCKER_HOST_IP}:9092
eventuateLocal.zookeeper.connectionString: ${DOCKER_HOST_IP}:2181
eventuateLocal.cdc.dbUserName: root
eventuateLocal.cdc.dbPassword: rootpassword